CREATE DATABASE ASMJAVAWEB_CONG_NO
GO
USE ASMJAVAWEB_CONG_NO
GO




CREATE TABLE LOAIHANG(
  MALOAIHANG NVARCHAR(100) PRIMARY KEY,
  TENLOAIHANG NVARCHAR(100)
)

CREATE TABLE HANGHOA(
  MAHANG NVARCHAR(100) PRIMARY KEY,
  TENHANG NVARCHAR(100),
  DONGIA INT,
  GIANHAP INT,
  TONDAU INT ,
  TONCUOI INT, 
  SLNHAP INT , 
  SLXUAT INT   
)

UPDATE HANGHOA SET SLXUAT=(SELECT SLXUAT+1 FROM HANGHOA WHERE MAHANG='hh00003') WHERE MAHANG='hh00003'


CREATE TABLE CHITIET_HANGHOA(
  MAHANG NVARCHAR(100) FOREIGN KEY REFERENCES HANGHOA(MAHANG),
  MALOAIHANG NVARCHAR(100) FOREIGN KEY REFERENCES LOAIHANG(MALOAIHANG),
  TINHNANG NVARCHAR(255),
  DVT NVARCHAR(100),
  TILE_GTGT FLOAT
)



CREATE TABLE LOAI_HOADON(
  MALOAI NVARCHAR(100) PRIMARY KEY,
  TENLOAI NVARCHAR(100)
)



CREATE TABLE KHACHHANG(
  MAKH NVARCHAR(100) PRIMARY KEY,
  TENKH NVARCHAR(100),
  DIACHI NVARCHAR(100),
  SDT NVARCHAR(100),
  EMAIL NVARCHAR(100),
  MASOTHUE NVARCHAR(100),
  PHAITHUDAUKY INT,
  DATHUDAUKY INT
)



CREATE TABLE NHANVIEN_KETOAN(
  MANV NVARCHAR(100) PRIMARY KEY,
  TENNV NVARCHAR(100),
  DIACHI NVARCHAR(100),
  SDT NVARCHAR(100),
  CMT NVARCHAR(100),
  TENDN NVARCHAR(100),
  PASS NVARCHAR(100),
  PHANQUYEN INT
)


CREATE TABLE HOADON(
  MAHD NVARCHAR(100) PRIMARY KEY,
  NGAYLAP DATE,
  MAKH NVARCHAR(100) FOREIGN KEY REFERENCES KHACHHANG(MAKH),
  MANV NVARCHAR(100) FOREIGN KEY REFERENCES NHANVIEN_KETOAN(MANV),
  TIENHANG INT,
  MALOAI NVARCHAR(100) FOREIGN KEY REFERENCES LOAI_HOADON(MALOAI) ,
  TIEN_GTGT INT,
  TRANGTHAI INT
)

CREATE TABLE HOADON_CHITIET(
  MAHD NVARCHAR(100) ,
  MAHANG NVARCHAR(100) FOREIGN KEY REFERENCES HANGHOA(MAHANG),
  SOLUONG INT ,
  DONGIA INT ,
  THANHTIEN INT, 
  TIENGTGT INT
)


SELECT SUM(CAST(THANHTIEN) ) 
FROM HOADON_CHITIET






SELECT HOADON.NGAYLAP,HOADON_CHITIET.MAHD,CHITIET_HANGHOA.TINHNANG,CONG_NO.TKNO,CONG_NO.TKCO,HOADON_CHITIET.THANHTIEN
FROM HOADON,HOADON_CHITIET,HANGHOA,CONG_NO,CHITIET_HANGHOA
WHERE 
HANGHOA.MAHANG = HOADON_CHITIET.MAHANG
AND CONG_NO.MAHD=HOADON_CHITIET.MAHD
AND HOADON.MAHD=HOADON_CHITIET.MAHD
AND CHITIET_HANGHOA.MAHANG=HANGHOA.MAHANG
AND HOADON.NGAYLAP  BETWEEN '2021-11-1' AND '2021-11-30';










CREATE TABLE CONG_NO(
  MACONGNO NVARCHAR(100) PRIMARY KEY ,
  NGAYLAP DATE,
  MAHD NVARCHAR(100) FOREIGN KEY REFERENCES HOADON(MAHD), 
  MAKH NVARCHAR(100) FOREIGN KEY REFERENCES KHACHHANG(MAKH) ,
  MANV NVARCHAR(100) FOREIGN KEY REFERENCES NHANVIEN_KETOAN(MANV) ,
  DIENGIAI NVARCHAR(100),
  SOTIEN INT ,
  TKCO INT,
  TKNO INT,
  TKNO_GTGT NVARCHAR(100)
)




CREATE TABLE PHIEUTHU(
  MAPHIEUTHU NVARCHAR(100) ,
  MAHD NVARCHAR(100),
  MAKH NVARCHAR(100),
  NGAYLAP DATE,
  DIENGIAI NVARCHAR(255),
  SOTIEN INT ,
  MANV NVARCHAR(100),
  TKNO int,
  TKCO int,
  TKCO_GTGT NVARCHAR(100)
)











CREATE TABLE PHIEUXUAT(
  MAPHIEUXUAT NVARCHAR(100) PRIMARY KEY  ,
  MAHD NVARCHAR(100),
  MAKH NVARCHAR(100),
  MANV NVARCHAR(100),
  NGAYXUAT DATE,
  TONGTIEN INT,
  DIENGIAI NVARCHAR(255)
)






CREATE TABLE XUAT_CHITIET(
  MAPHIEUXUAT NVARCHAR(100) FOREIGN KEY REFERENCES PHIEUXUAT(MAPHIEUXUAT),
  MAHANG NVARCHAR(100),
  SOLUONG INT,
  DONGIA INT,
  THANHTIEN INT ,
)









SELECT CONG_NO.MAKH,KHACHHANG.TENKH,TKNO AS TKNO_DAUKY ,TKCO AS TKCO_DAUKY 
FROM CONG_NO ,KHACHHANG
WHERE KHACHHANG.MAKH=CONG_NO.MAKH
AND MACONGNO IN (SELECT  MIN(MACONGNO) FROM CONG_NO GROUP BY MAKH) 
AND  NGAYLAP BETWEEN '2021-11-1' AND '2021-11-30'
 

SELECT CONG_NO.MAKH,SUM(TKNO)AS TKNO_CUOIKY,SUM(TKCO) AS TKCO_CUOIKY 
FROM CONG_NO ,KHACHHANG
WHERE KHACHHANG.MAKH=CONG_NO.MAKH
GROUP BY KHACHHANG.MAKH ,CONG_NO.MAKH

SELECT SUM(TKNO)AS TKNO_CUOIKY,SUM(TKCO) AS TKCO_CUOIKY 
FROM CONG_NO 
GROUP BY MAKH




SELECT PHIEUTHU.NGAYLAP ,
FROM HOADON,HANGHOA,KHACHHANG,PHIEUTHU,HOADON_CHITIET
WHERE KHACHHANG.MAKH=HOADON.MAKH
AND HANGHOA.MAHANG=HOADON_CHITIET.MAHANG
AND HOADON.MAHD=HOADON_CHITIET.MAHD
AND PHIEUTHU.MAKH=KHACHHANG.MAKH
AND KHACHHANG.MAKH='KH00001'




SELECT CONG_NO.NGAYLAP,CONG_NO.MAHD,CONG_NO.DIENGIAI,HOADON.TIENHANG,CONG_NO.TKCO
FROM CONG_NO,KHACHHANG,HOADON
WHERE KHACHHANG.MAKH=CONG_NO.MAKH
AND HOADON.MAHD=CONG_NO.MAHD
AND KHACHHANG.MAKH='KH00001' AND KHACHHANG.TENKH='Nguyen thanh tung'
SELECT COUNT(*) FROM HOADON_CHITIET WHERE MAHD='HD00001'



SELECT HOADON.MAHD,HOADON.NGAYLAP,HOADON.MAKH,HOADON.MANV,HOADON.MALOAI,HOADON_CHITIET.MAHANG,HOADON_CHITIET.SOLUONG,HOADON_CHITIET.DONGIA,HOADON_CHITIET.THANHTIEN,HOADON_CHITIET.TIENGTGT
FROM HOADON_CHITIET
LEFT OUTER JOIN HOADON
ON HOADON_CHITIET.MAHD = HOADON.MAHD 
where HOADON.MAHD like 'hd00001'or HOADON.MALOAI  like 'LHD00001'  or HOADON.NGAYLAP like '2021-11-01'
SELECT MAKH FROM HOADON WHERE MAHD='hd00001'


























